Fixes for USB-connected keyboard and trackpad
VoodooI2C/VoodooI2CHID pull request #52
Opened 2021-03-13 03:29 UTC by Xiashangning

The keyboard patch is from `https://github.com/shdkpr2008/VoodooI2CHID.git`'s VoodooI2CMultitouchHIDEventDriver.cpp/hpp. Probably this is the solution for all USB-connected detachable keyboard&trackpad like Surface series, 2 in 1 laptops etc.

2021-03-16 11:51 UTC, kprinssu commented
Thanks @Xiashangning, I'll be creating a PR review.

@ben9923 can you please also take a look.

2021-03-16 12:06 UTC, kprinssu requested changes

2021-03-16 12:06 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +                    kbEnableEventProps->release();
`OSSafeReleaseNULL` would be better here.

2021-03-16 12:06 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +                    kbEnableEventProps->release();
In fact why even allocate `kbEnableEventProps` if it's not being used?

2021-03-16 12:29 UTC, Xiashangning commented
Got it, in fact it is my bad not to examine through the code before I submit this PR, I just `copy` what in his code without thinking carefully what he has done, since I have been using this patch for quite a few days and no KP is met, I will try to ameliorate it and then test it to see if something unexcepted would happen.

2021-03-16 12:31 UTC, kprinssu commented
@Xiashangning No problem, it's mostly stylistic an d nothing major in general, but a huge thanks for creating the PR!

2021-03-16 13:43 UTC, Xiashangning commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +    if ( (volumeState != 0x7) && (volumeHandled != 0x7) ) {
Like a single .h header file? I would name it `VoodooI2CHIDKeyboardConstants.h`, but there are only three constants right now... So maybe `#define kHIDIncVolume 0x01`?

2021-03-16 22:57 UTC, ben9923 commented
Thanks for the PR :)

Until I can properly review it, I must say putting the keyboard code in the multitouch event driver seems like the wrong idea.
Ideally another event driver should attach to the same IOHIDInterface and handle keyboard reports.

BTW, can you attach a copy of IOReg from your machine? I'd like to see how the matching can be done there, when separated into a dedicated keyboard event driver.

2021-03-17 15:36 UTC, Xiashangning commented
@kprinssu I have made the required improvement, the magic constants are define at the head of 
`VoodooI2CMultitouchHIDEventDriver.cpp`.
@ben9923 Here it is. It's under XHC/HS08
[Surface Pro 7 ioreg.zip](https://github.com/VoodooI2C/VoodooI2CHID/files/6157439/Surface.Pro.7.ioreg.zip)

BTW, you can see that there is another I2C controller presented in my IO reg(`I2C4`), it has a device id of `34c5` which is not supported by VoodooI2C. However, it has an ambient light sensor attached under it and the code from Linux is very simple to port. I have searched through VoodooI2C but cannot find how the `VoodooI2CPCILakeController` is matching against these devices, I can only find 0x34e8 in the IOKitPersonalities. I would like to try adding 34c5 and test if it is compatible, how should I do? Thanks

2021-03-19 20:14 UTC, ben9923 commented
@Xiashangning Thanks for the IOReg :)
So indeed that driver can match usage page 1, usage 6 (Which means keyboard).
I'm not sure if another driver can just match under the same IOHIDInterface, or we should make some changes to allow both to load at the same time...
If you remove the `VoodooI2CMultitouchHIDEventDriver` personality from VoodooI2CHID's Info.plist, does any other driver load instead? Does the keyboard work in that case? Please attach an IOReg with it disabled :)

Anyway, the keyboard code cannot be a part of the multitouch code. They are completely unrelated to each other.

As for `8086:34c5`, you can just add `34cX` to the `VoodooI2CPCILakeController` personality in the Info.plist.
For example, you can see `0x34e88086&0xFFFCFFFF` there. It'll match any device with PCI ID `8086:34eX`, Just add `0x34c58086&0xFFFCFFFF` to the same PCI matching.

2021-03-21 15:32 UTC, Xiashangning commented
@ben9923 Hello, I have made a dedicated keyboard driver `VoodooI2CKeyboardHIDEventDriver`, using your recommended match pairs. As you can see in the attached IOReg, only the Keyboard Driver is activated, macOS fails to load multitouch driver...
I have committed my changes. Frankly speaking, I do not know too much about kext development, still learning :) So please take a look at my code and tell me if I have done anything wrong.
[Surface Pro 7 dedicated Keyboard Driver.zip](https://github.com/VoodooI2C/VoodooI2CHID/files/6177755/Surface.Pro.7.dedicated.Keyboard.Driver.zip)

2021-03-28 08:19 UTC, ben9923 commented
@Xiashangning Cool :)
Did you also check the case when VoodooI2C doesn't load under it at all? Does any Apple keyboard driver attach to the device?

Seems like only one event driver may load under an `IOHIDInterface`. Someone should find the appropriate method to make use of both, either by a third event driver that decorates the other two, or by any other way that would allow both to attach at the same time.

I just checked how my keyboard + mouse receiver works - It simply exposes multiple `IOHIDInterface`s...

2021-04-27 07:24 UTC, 1Revenger1 commented on VoodooI2CHID/Info.plist
> +			<key>IOClass</key>
```suggestion
                        <key>IOMatchCategory</key>
                        <string>VoodooI2CKeyboardHIDEventDriver</string>
			<key>IOClass</key>
```
The string can be whatever you want, but having different categories for matching should allow multiple services to probe + attach

2021-05-16 10:10 UTC, kingo132 commented
This patch does not support caps lock led on the surface type cover. I read the code of VoodooPS2 tries to find how to toggle this caps led. But it seems very different from ApplePS2KeyboardDevice (used by VoodooPS2) to IOHIDEventService (used by your patch). I tried to add some code to toggle caps led. They all failed. Could you please add this led toggle?

2021-08-06 08:25 UTC, therealjbenam commented
Any news on getting this merged in VoodooI2C, @Xiashangning ?

I have compiled the kext with your patches and it works wonderfully on my Surface Pro 6. Finally no more KPs when closing the lid (which means I can now also use it in "docked" mode, with the lid closed and an external monitor and keyboard, yay)!

2021-08-06 10:10 UTC, Xiashangning commented
@therealjbenam sorry, it seems that there is concern about putting keyboard related codes in trackpad&i2c kext(which is the nature of this repo),so instead of merging it, i have already created my repo forked from this repo and add them myself. Since my kext is dedicated for SP users, mixing these codes together is fine for me. :D
You can use that kext instead, i will update it along with voodooi2c. 
Hence this pr will be closed(sorry for leaving this pr for so long, i forgot to close it…)

2021-08-06 10:10 UTC, closed without merging