Fix report parsing for devices with multi-mode (trackpad or touchscreen) capabilities
VoodooI2C/VoodooI2CHID pull request #58
Opened 2021-12-23 01:10 UTC by gvkt

This provides a fix for correctly parsing the report descriptor for the desired mode in a multi-mode device such as the Asus Screenpad (e.g., as trackpad or as touch screen).

In such devices the same elements (e.g., contact count) can exist in multiple sections in the report descriptor. While parsing the report descriptor, the current code assumes a single mode and parses all elements that can work in any mode. Depending on the order in which the record descriptor elements are parsed, the wrong object may be cached for reporting for the mode in which the satellite driver is using the device in. 

This results in symptoms such as multi-touch not being available for such a device as the contact count element object cached may be for the wrong mode for the mode in which the device is being used. That cached object will then not update as reports come in for the device in desired mode.

The fix allows the specialized device event drivers such as PrecisionTrackpad or TouchScreen to control the parsing and caching for their respective modes only.

This fix has no known side-effects (not tested with pen/stylus capability) and has fixed multi-touch unavailability problem for the Asus Screenpad working as a trackpad and the second screen of Asus Duo laptops working as touch screen.

2021-12-23 15:11 UTC, kprinssu requested changes

2021-12-23 15:11 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +IOReturn VoodooI2CMultitouchHIDEventDriver::parseElements(UInt32 forUsage) {
Can you please consider a name change to just usage (see https://developer.apple.com/documentation/kernel/iohidelement/1426848-conformsto)

2021-12-23 15:11 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +    if (parseElements(0) != kIOReturnSuccess) {
What does `0` imply here, it's more or less a magic constant? Can you use a constant from IO Kit?

2021-12-23 15:11 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.hpp
> +    virtual IOReturn parseElements(UInt32 forUsage=0);
Please document what `forUsage` parameter is and does.

2021-12-23 15:11 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CPrecisionTouchpadHIDEventDriver.hpp
> +    IOReturn parseElements(UInt32 forUsage=0) override;
Please replace the magic constant `0` with a header declaration or a proper equivalent from IO Kit.

2021-12-23 15:11 UTC, kprinssu commented on VoodooI2CHID/VoodooI2CMultitouchHIDEventDriver.cpp
> +            if (multitouch_interface && element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_TouchScreen))
Why not roll the if statement into one as:
`( *!forUsage || (forUsage == kHIDUsage_Dig_TouchScreen)) && multitouch_interface && element->conformsTo(kHIDPage_Digitizer, kHIDUsage_Dig_TouchScreen))`

Perhaps adding a multi-line condition would be more readable but I am not a fan of nested if statements.

2021-12-23 15:32 UTC, gvkt commented on README.md
> +This is a fork with a fix for the Precision Trackpad and Touch Screen Trackpad satellites to work correctly for devices that can work with multiple modes (trackpad or touch screen).
I wrote the README to explain what the fork was about and it automatically got included in the changes. Still haven't figured out how to withdraw or reject an item for this purpose. New to this.

2021-12-23 15:39 UTC, gvkt commented
I am fine with whatever stylistic changes you guys want. That is neither my strong point nor productive use of my time. Spent far too much time already with the steep learning curve starting from zero knowledge to figure out the problem and a proof of concept solution to make sure it works. Didn't plan on becoming a Voodoo developer.

I will leave it to whoever is motivated and have the time on how best to incorporate into the existing code base if they believe this problem is worth fixing. Have a bunch of issues still to fix with my Hackintosh before I actually use it for productive work. :) 

Hope the time I spent was worth it to more than just me.

2021-12-23 17:32 UTC, kprinssu commented
No worries @gvkt 

Thanks for the PR. I'll reopen it but myself or @ben9923 can change it. I'll reopen this so we can actually track the changes.

2021-12-23 17:38 UTC, ben9923 commented
@gvkt Thanks for your work!

We might be able to make it a bit cleaner, by checking whatever usage was the driver matched by, but I'm not sure how it'll work for the generic multitouch driver.
I'll try to work on that :)

2021-12-24 01:31 UTC, gvkt commented
@ben9923  I thought a little bit about the solution before the quick fix for my specific use case. So, I will put them down here to guide any solution.

I kept the changed code in MultiTouchEventDriver separated visually so that its behavior and usage in existing hardware where it is attached directly rather than the PTP or TouchScreen specializations is exactly as before and minimal perturbation without creating any regression issues. I see this as just a quick short term hack.

To be conceptually clean and correct, MultiTouchEventDriver code requires a non-trivial rewrite to make the "digitizer" variable as an indexed array for each "collection" in the report descriptor, indexed by the unique Report ID. So there would be separated digitizer object lists for mouse collection, trackpad collection, touchscreen collection, etc as may be present in the type descriptor each indexed with its own unique Report ID. During parsing, the child element objects would go into the corresponding digitizer collection rather than be squished into a single list as it happens now with element objects from different collections overwriting each other depending on the order in which they are processed.

When a report comes in for any collection, the report id would be used to pick the cached digitizer object collection that would reflect the data from that report.

If this is done, then no change would be necessary for PTP or Touchscreen event drivers. The changes in this PR to the specializations would be unnecessary except perhaps as an optimization to narrow the parsing/caching to only a single collection when the usage mode is known and static.

So, I see this quick fix suitably cleaned up as a short term temporary solution to fix existing issues with contemporary laptops. I don't see any future laptop use cases likely that there would be a multi-touch device that is multi-modal but neither a precision trackpad nor a touch screen. So, in theory, the generic MultiTouch event driver wouldn't attach directly to any device except perhaps for some legacy devices that aren't PTP compliant.

The longer term solution as described above should be addressed in a rethink of which and how event drivers will be assigned to a device in the first place. In laptops like the Zenbook and likely in most future laptops following Windows guidelines, the trackpad, the touch screen, etc will all be I2C HID devices differentiated in their properties only with a product ID (and in some cases vendor ID). So, the current scheme of automatic selection based on some probe score will not work correctly. The OOB kext even with this quick fix would not be usable for new Zenbook laptops such as mine without manually modifying the Info.plist to force the correct event driver to each device based on matching the product ID or some other differentiating property unrelated to their desired function.

Moreover, as currently happens in Zenbooks under Windows, that mode selection for a device is actually dynamic and user selectable during a booted session (e.g., screenpads). So a longer term solution such as the one described above would even make it potentially possible for a dynamic selection in a Hackintosh if use cases presented themselves in this context.

Hope that helps. Happy to test any beta releases in the future with my laptops for the fixes related to this.

2022-01-22 12:21 UTC, narcyzzo commented
can this be merged sometimes? many guys having touchscreens have issues with multi-mode so that will be great.

2022-01-22 13:01 UTC, kprinssu commented
> can this be merged sometimes? many guys having touchscreens have issues with multi-mode so that will be great.

Not as it is as there are a lot of glaring issues. @gvkt has already mentioned they will not be working on this further. I personally do not have the time to make the changes neither, but follow up PRs are welcome.

2022-01-22 13:02 UTC, narcyzzo commented
to be dead honest this is working. I tested it, so it just need code style poloshing isnt?

2022-01-22 13:13 UTC, kprinssu commented
> to be dead honest this is working. I tested it, so it just need code style poloshing isnt?

Cool. Yes, give the PR comments a go and if you want to work on the changes, great. As I said before, PRs are always welcome.

2022-01-24 03:07 UTC, 1Revenger1 commented
So I was looking to possibly pick this up. I'm not sure that switching dynamically between a trackpad and touchscreen is possible, especially with the current VoodooI2CHID architecture.  VoodooI2C in the Info.plist looks at usagepage/usage and only will take the one which has the highest score. You might be able to get both to attach if they filtered their own report IDs, as well as giving each their own IOMatchCategory. There would still be the issue of configuring which one was enabled/disabled though, which would require probably some sort of userspace application and Asus specific kext which looked at hotkeys which would both be outside the scope of this project.

Is there a way to configure the screenpad to act as a trackpad or touchscreen, or does it send both types of reports at the same time? I notice that they have different report IDs.

I think for now, the option of just filtering for the Touchpad or Touchscreen elements works just fine. If the Precision Trackpad event driver has the highest probe score, that should be the one used by default, and should be fine for hopefully 80% of cases? I'm not sure how this would affect stylus though.

I'm willing to pick this up (I'm bored), though I don't have anyway to test so I'd appreciate a couple testers once I post a build.

As an aside, does anyone know if devices like the Asus Duo work fine? I think they have two touchscreens plus whatever the touchpad does.

2022-01-24 03:50 UTC, gvkt commented
I have probably looked at the ASUS specifics of this more than anyone else at the moment. While I am not a hard coder, happy to share my findings, architecture suggestions and beta test.

> So I was looking to possibly pick this up. I'm not sure that switching dynamically between a trackpad and touchscreen is possible, especially with the current VoodooI2CHID architecture. 

The only way this might work as I have indicated in another thread is having a single driver that attaches to all and every i2c HID device and then acts as a dynamic router to "plugin" drivers based on report id. This itself wouldn't care about what the device is configured as or how one might switch between them which would be application level switching that someone else can provide. But this is a significant rewriting of the architecture. This would neatly solve the issues below and would be backward compatible.

> VoodooI2C in the Info.plist looks at usagepage/usage and only will take the one which has the highest score. You might be able to get both to attach if they filtered their own report IDs, as well as giving each their own IOMatchCategory. There would still be the issue of configuring which one was enabled/disabled though, which would require probably some sort of userspace application and Asus specific kext that looked at hotkeys. These would both be outside the scope of this project.
> 
From what I have seen here, increasingly all of these I2C HID input devices are going to look the same at the driver level and so the current match scoring is not going to work. These devices whether the Screenpad 2.0 that is primarily a touchpad or the secondary screen on duos which is primarly a touch screen will match the same driver (whatever it is). So in my case, the multi-touch screen driver will attach to both Screenpad 2.0 and to the touch (main) screen. If you fiddle around with weights to make PTP driver attach to the Screenpad, then something else will attach to the main screen stopping it from working as a touch screen.

My suggestion for doing this in simple steps:

1. Merge the code I have with whatever stylistic changes into the main. This will work as is for the typical trackpad touch-screen configurations.
2. For Zenbooks with Screenpad and Duos with secondary screen, a manual assignment is needed in addition (and independent of the above) to force the assignment of the correct driver for each. I have done this by modifying the info.plist to match product id. But a solution where this can be done with perhaps a boot argument is probably a more usable solution.

The above will take care of all of the devices for now with minimal changes.

The flow re-architecting could be a longer term goal.

2022-01-24 07:35 UTC, 1Revenger1 commented
> The only way this might work as I have indicated in another thread is having a single driver that attaches to all and every i2c HID device and then acts as a dynamic router to "plugin" drivers based on report id. This itself wouldn't care about what the device is configured as or how one might switch between them which would be application level switching that someone else can provide. But this is a significant rewriting of the architecture. This would neatly solve the issues below and would be backward compatible.

I agree to an extent. It looks like Linux has a quirk which allows multiple drivers per HID device to appear. I'm fairly certain that we would only need to keep track of plugins per HID device, correct? Also does the device report both Trackpad and Touchscreen reports at the same time, or is that configured when setting the mode of the device (ie 0x3 for touchpad and 0x2 for touchscreen).

> From what I have seen here, increasingly all of these I2C HID input devices are going to look the same at the driver level and so the current match scoring is not going to work. These devices whether the Screenpad 2.0 that is primarily a touchpad or the secondary screen on duos which is primarly a touch screen will match the same driver (whatever it is). So in my case, the multi-touch screen driver will attach to both Screenpad 2.0 and to the touch (main) screen. If you fiddle around with weights to make PTP driver attach to the Screenpad, then something else will attach to the main screen stopping it from working as a touch screen.

I think the match score does sort of work for most devices. Most devices released today have a regular trackpad and a touchscreen. It's mostly Asus with these confusing configurations lol. Just for clarity, screenpads are represented as a single HID device which reports both the Touchscreen and Touchpad usages, correct? What does a Duo device look like to the OS? Also what about that crazy calculator thing?

Sorry for all the questions. Just trying to figure out if it's just screenpads that have the issue or other Asus models as well.

2022-01-24 08:09 UTC, williambj1 commented
> What does a Duo device look like to the OS?

My friend owns a first gen Zephyrus Duo and I installed macOS on that device a year ago (unfortunately I don't have access to that device anymore). The secondary screen at the bottom works as a normal touchscreen and everything is working as expected (multi finger input, gestures, etc) with the latest release at that time.

> Also what about that crazy calculator thing?

I personally own an 8th gen Intel Zephyrus S and it has one of those numpad/trackpad on it. This driver[1] works in linux. Looking at the source code it seems that a i2c command is need to activate the lights for the numbers and the touch input needs to be divided into regions for each num key.

\[1\]: https://github.com/mohamed-badaoui/asus-touchpad-numpad-driver/blob/main/asus_touchpad.py#L153

2022-01-24 14:11 UTC, narcyzzo commented
from what i know Duo devices has different I2C touchscreen its, ELAN1200, see this here : 
https://github.com/deniro98/hackintosh-asus-zenbook-duo-ux482ea

2022-01-24 14:13 UTC, narcyzzo commented
Asus Duo devices probably have another I2C device? Like here, ELAN1200 
https://github.com/deniro98/hackintosh-asus-zenbook-duo-ux482ea
@deniro98 mayby u can told something more about how this screen is working?

2022-01-25 04:19 UTC, 1Revenger1 commented
Thanks. I think I have a somewhat better insight into the issue now. I think for now I'll work through the changes requested above, and come back at a later time. I'll see if I can think up of something better.

Also, I've been looking through IOHIDFamily and found the property `kIOHIDMultipleInterfaceEnabledKey`, which seems to allow an IOHIDInterface to appear for every top level collection in the report descriptor... Pretty sure 3/4 interfaces would appear for the Screenpad, which sounds like a lot of chaos (Mouse/Touchpad/Touchscreen/Some vendor specific device). If anyone knows more about this property, feel free to say something.

~~If someone feels like breaking things and is crazy, it'd be interesting to see what happens if the multiple interface key property is set in VoodooI2CHIDDevice::handleStart before super::handleStart is called.~~

2022-01-25 06:15 UTC, gvkt commented
> I agree to an extent. It looks like Linux has a quirk which allows multiple drivers per HID device to appear. I'm fairly certain that we would only need to keep track of plugins per HID device. Does the device report both Trackpad and Touchscreen reports at the same time, or is that configured when setting the mode of the device (ie 0x3 for touchpad and 0x2 for touchscreen)?

The report descriptor contains all the collections it will report on but I believe the reporting is only for the mode it is set to.

> Just for clarity, screenpads are represented as a single HID device which reports both the Touchscreen and Touchpad usages, correct? 

Yes

> What does a Duo device look like to the OS? Also what about that crazy calculator thing?

Both screenpads and duo screens look like multiple video displays and multiple I2C HID devices. Two separate I2C HID devices (or 3 if they also have a trackpad in addition to two screens like the Zenbook Pro Duo).

The calculator, etc are all software running on the second display as a touch screen nothing to do with the devices themselves. There is also a software trackpad overlay
to temporarily use it as a trackpad without switching modes. This is all at application level.

From driver perspective, there is a function key to switch the mode to pure trackpad (relative co-ordinates) or to display touch screen (absolute co-ordinates) or completely disable it. Linux cannot do this. Only on Windows.

2022-01-25 14:37 UTC, kprinssu commented
I am closing this PR in favour of https://github.com/VoodooI2C/VoodooI2CHID/pull/59

2022-01-25 14:37 UTC, closed without merging

2022-01-25 16:20 UTC, 1Revenger1 commented
> Both screenpads and duo screens look like multiple video displays and multiple I2C HID devices. Two separate I2C HID devices (or 3 if they also have a trackpad in addition to two screens like the Zenbook Pro Duo).
> 
> From driver perspective, there is a function key to switch the mode to pure trackpad (relative co-ordinates) or to display touch screen (absolute co-ordinates) or completely disable it. Linux cannot do this. Only on Windows.

Cool, that makes sense. Instead of worry about multiple plugins possibly, could we have the multitouch plugin check for both types of collections and then just choose one? If we had one event driver that handled everything, then we wouldn't need to bother with trying to attach multiple plugins and switching between them.

This also means we could have a userspace program potentially set a property and have the trackpad switch modes real quick.